FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=run
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["sh", "-c", "flask create_tables && flask run"]